config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users
  resources :users
  resources :events do
    resources :enrollments, only: [:new, :create, :destroy]
    member do
      get 'attend'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  
  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"
    has_many :enrollments, foreign_key: :attended_event_id
    has_many :attendees, through: :enrollments

  scope :past, -> { where('date <= ?', Date.today)}
  scope :future, -> { where('date > ?', Date.today)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_events, foreign_key: :creator_id, class_name: "Event"
  
  has_many :enrollments, foreign_key: :attendee_id
  has_many :attended_events, through: :enrollments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
    
    
  
    private

    def enrollments_params
      params.require(:enrollment).permit(:attended_event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :create]

  # GET /events or /events.json
  def index
    @events = Event.all
    @event = Event.new
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def attend
    @event = Event.find(params[:id])

    enrollment = Enrollment.new(attendee_id: current_user.id, attended_event_id: @event.id)
    if @event.attendees.include?(current_user)
      redirect_to @event, notice: "You're already on the list!"
    elsif enrollment.save
      redirect_to @event, notice: "You are now attending this event!"
    else
      redirect_to @event, alert: "You are already attending this event!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :location, :date, :body, :creator_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
    
    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @users = current_user.created_events.all
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Title:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= event.body %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Upcoming Events</h1>

<div id="events">
  <% @events.future.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>

<h1>Past Events</h1>

<div id="events">
  <% @events.past.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>
<%= link_to "New event", new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>Event</h1>
<%= render @event %>
<h2>Attendees</h2>
  <% @event.enrollments.each do |attendee| %>
      <li><%= User.find(attendee.attendee_id).email %> </li>
<br>
  <% end %>

<br>
<br>
<div>
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to events", events_path %>
  <%= link_to 'Attend', attend_event_path(@event) %>
  <%= button_to "Destroy this event", @event, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <header>
    <h1>PrivateEvents</h1>

    <% if user_signed_in? %>
      <%= link_to "Events", events_path %>
      <%= link_to "Sign out", destroy_user_session_path %>
      <%= link_to "New Event", new_event_path %>
      <%= link_to "Profile", user_path(current_user) %>
      <%= link_to current_user.email, edit_user_registration_path %>

    <% else %>
       <%= link_to 'Sign In', new_user_session_path %>
       <%= link_to 'Sign Up', new_user_registration_path %>
            
    <% end %>
  
  
  </header>
  
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= current_user.email %>, these are the events you've created</h1>


  <% current_user.created_events.each do |event| %>
    <li><%= event.title %></li>
    <br>
  <% end %>


 <h1>Here are your upcoming events.</h1>
<% current_user.attended_events.future.each do |event| %>
    <li><%= event.title %></li>
    <br>
    
  <% end %>

<h1>These are the events you've attend.</h1>
<% current_user.attended_events.past.each do |event| %>
    <li><%= event.title %></li>
    <br>
    
  <% end %>

 


  